{{- if .Values.credentials.create -}}
{{- include "upcloud-ccm.validate" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "upcloud-ccm.secretName" . }}
  namespace: {{ include "upcloud-ccm.namespace" . }}
  labels:
    {{- include "upcloud-ccm.labels" . | nindent 4 }}
  {{- with (include "upcloud-ccm.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.credentials.usernameKey }}: {{ .Values.credentials.username | quote }}
  {{ .Values.credentials.passwordKey }}: {{ .Values.credentials.password | quote }}
{{- end }}
