{{- /* Vendored from the upstream v4.17.0 driver.yaml and
       snapshot-controller.yaml RBAC blocks. */ -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "digitalocean-csi.fullname" . }}-controller-sa
  namespace: {{ include "digitalocean-csi.namespace" . }}
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "digitalocean-csi.fullname" . }}-node-sa
  namespace: {{ include "digitalocean-csi.namespace" . }}
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
{{- if .Values.snapshotController.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "digitalocean-csi.fullname" . }}-snapshot-controller-sa
  namespace: {{ include "digitalocean-csi.namespace" . }}
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "digitalocean-csi.fullname" . }}-provisioner-role
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "digitalocean-csi.fullname" . }}-provisioner-binding
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "digitalocean-csi.fullname" . }}-controller-sa
    namespace: {{ include "digitalocean-csi.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "digitalocean-csi.fullname" . }}-provisioner-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "digitalocean-csi.fullname" . }}-attacher-role
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "digitalocean-csi.fullname" . }}-attacher-binding
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "digitalocean-csi.fullname" . }}-controller-sa
    namespace: {{ include "digitalocean-csi.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "digitalocean-csi.fullname" . }}-attacher-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "digitalocean-csi.fullname" . }}-snapshotter-role
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents/status"]
    verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "digitalocean-csi.fullname" . }}-snapshotter-binding
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "digitalocean-csi.fullname" . }}-controller-sa
    namespace: {{ include "digitalocean-csi.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "digitalocean-csi.fullname" . }}-snapshotter-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "digitalocean-csi.fullname" . }}-resizer-role
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "digitalocean-csi.fullname" . }}-resizer-binding
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "digitalocean-csi.fullname" . }}-controller-sa
    namespace: {{ include "digitalocean-csi.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "digitalocean-csi.fullname" . }}-resizer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "digitalocean-csi.fullname" . }}-node-driver-registrar-role
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "digitalocean-csi.fullname" . }}-node-driver-registrar-binding
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "digitalocean-csi.fullname" . }}-node-sa
    namespace: {{ include "digitalocean-csi.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "digitalocean-csi.fullname" . }}-node-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.snapshotController.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "digitalocean-csi.fullname" . }}-snapshot-controller-role
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents/status"]
    verbs: ["patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots/status"]
    verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "digitalocean-csi.fullname" . }}-snapshot-controller-binding
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "digitalocean-csi.fullname" . }}-snapshot-controller-sa
    namespace: {{ include "digitalocean-csi.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "digitalocean-csi.fullname" . }}-snapshot-controller-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
