{{- if .Values.credentials.create -}}
{{- include "digitalocean-csi.validate" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digitalocean-csi.secretName" . }}
  namespace: {{ include "digitalocean-csi.namespace" . }}
  labels:
    {{- include "digitalocean-csi.labels" . | nindent 4 }}
  {{- with (include "digitalocean-csi.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.credentials.tokenKey }}: {{ .Values.credentials.token | quote }}
{{- end }}
