{{- if .Values.credentials.create -}}
{{- include "digitalocean-ccm.validate" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digitalocean-ccm.secretName" . }}
  namespace: {{ include "digitalocean-ccm.namespace" . }}
  labels:
    {{- include "digitalocean-ccm.labels" . | nindent 4 }}
  {{- with (include "digitalocean-ccm.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.credentials.tokenKey }}: {{ .Values.credentials.token | quote }}
{{- end }}
