{{- if .Values.credentials.create -}}
{{- include "upcloud-csi.validate" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "upcloud-csi.secretName" . }}
  namespace: {{ include "upcloud-csi.namespace" . }}
  labels:
    {{- include "upcloud-csi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.credentials.usernameKey }}: {{ .Values.credentials.username | quote }}
  {{ .Values.credentials.passwordKey }}: {{ .Values.credentials.password | quote }}
{{- end }}
