{{- if .Values.storageClasses.hdd.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.hdd.name }}
  labels:
    {{- include "upcloud-csi.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.storageClasses.defaultClass "hdd" }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- else }}
    storageclass.kubernetes.io/is-default-class: "false"
    {{- end }}
    {{- with .Values.storageClasses.hdd.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
provisioner: storage.csi.upcloud.com
parameters:
  tier: hdd
  {{- with .Values.storageClasses.hdd.extraParameters }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
reclaimPolicy: {{ .Values.storageClasses.hdd.reclaimPolicy | default .Values.storageClasses.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClasses.hdd.volumeBindingMode | default .Values.storageClasses.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageClasses.allowVolumeExpansion }}
{{- $topologies := default .Values.storageClasses.allowedTopologies .Values.storageClasses.hdd.allowedTopologies }}
{{- with $topologies }}
allowedTopologies:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.storageClasses.hdd.mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
