{{- if .Values.storageClasses.maxiops.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.maxiops.name }}
  labels:
    {{- include "upcloud-csi.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.storageClasses.defaultClass "maxiops" }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- else }}
    storageclass.kubernetes.io/is-default-class: "false"
    {{- end }}
    {{- with .Values.storageClasses.maxiops.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
provisioner: storage.csi.upcloud.com
parameters:
  tier: maxiops
  {{- with .Values.storageClasses.maxiops.extraParameters }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
reclaimPolicy: {{ .Values.storageClasses.maxiops.reclaimPolicy | default .Values.storageClasses.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClasses.maxiops.volumeBindingMode | default .Values.storageClasses.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageClasses.allowVolumeExpansion }}
{{- $topologies := default .Values.storageClasses.allowedTopologies .Values.storageClasses.maxiops.allowedTopologies }}
{{- with $topologies }}
allowedTopologies:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.storageClasses.maxiops.mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
