{{- if and .Values.originIssuer.enabled .Values.originIssuer.secret.create -}}
{{- include "cloudflare-operator.validate" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-operator.originIssuerSecretName" . }}
  namespace: {{ .Values.originIssuer.secret.namespace }}
  labels:
    {{- include "cloudflare-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.originIssuer.secret.key }}: {{ .Values.originIssuer.secret.token | quote }}
{{- end }}
