{{- if .Values.credentials.create -}}
{{- include "cloudflare-operator.validate" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-operator.cloudflareSecretName" . }}
  namespace: {{ include "cloudflare-operator.namespace" . }}
  labels:
    {{- include "cloudflare-operator.labels" . | nindent 4 }}
  {{- with (include "cloudflare-operator.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.credentials.apiTokenKey }}: {{ .Values.credentials.apiToken | quote }}
  {{ .Values.credentials.accountIdKey }}: {{ .Values.credentials.accountId | quote }}
{{- end }}
