{{- if .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cloudflare-operator.fullname" . }}
  namespace: {{ default (include "cloudflare-operator.namespace" .) .Values.metrics.serviceMonitor.namespace }}
  labels:
    {{- include "cloudflare-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "cloudflare-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/subcomponent: metrics
  namespaceSelector:
    matchNames:
      - {{ include "cloudflare-operator.namespace" . }}
  endpoints:
    - port: https
      scheme: https
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        {{- toYaml .Values.metrics.serviceMonitor.tlsConfig | nindent 8 }}
      {{- with .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
