apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflare-operator.fullname" . }}-webhook
  namespace: {{ include "cloudflare-operator.namespace" . }}
  labels:
    {{- include "cloudflare-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "cloudflare-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: {{ .Values.webhook.servicePort }}
      protocol: TCP
      targetPort: webhook
